#!/bin/bash


tmp_file=/tmp/code_terminal

start_proxy='echo " sudo service anonsurf start" > /tmp/code_terminal'
stop_proxy='echo " sudo service anonsurf stop" > /tmp/code_terminal'
change_proxy='echo " sudo service anonsurf change" > /tmp/code_terminal'
status_proxy='echo " sudo service anonsurf status" > /tmp/code_terminal'

my_ip='echo " sudo service anonsurf myip" > /tmp/code_terminal'

iceweasel_tor='echo "sudo service anonsurf iceweasel_tor" > /tmp/code_terminal'

tor_chat='/usr/bin/torchat &'

pandora_manager='gksu pandora-manager'

start_i2p='echo " sudo service anonsurf starti2p" > /tmp/code_terminal'
stop_i2p='echo " sudo service anonsurf stopi2p" > /tmp/code_terminal'

dim='20'

export MAIN_DIALOG='
<window window_position="1" title="AnonSurf" resizable="false" image-name="emblem-people">
	<vbox>
		<hbox>
			<frame>
				<frame Anonymous Mode>
					<button tooltip-text="Start AnonSurf">
						<input file>/opt/anonsurf/icons/play.svg</input>
						<width>'$dim'</width>
						<label> START </label>
						<action>'$start_proxy'</action>
						<action type="refresh">terminale</action>
					</button>
					<button tooltip-text="Stop AnonSurf">
						<input file>/opt/anonsurf/icons/stop.svg</input>
						<width>'$dim'</width>
						<label> STOP </label>
						<action>'$stop_proxy'</action>
						<action type="refresh">terminale</action>	    
					</button>
					<button tooltip-text="Change AnonSurf">
						<input file>/opt/anonsurf/icons/reload.svg</input>
						<width>'$dim'</width>
						<label> CHANGE IDENTITY </label>
						<action>'$change_proxy'</action>
						<action type="refresh">terminale</action> 
					</button>
					<button tooltip-text="Status AnonSurf">
						<input file>/usr/share/icons/Humanity/actions/24/stock_media-stop.svg</input>
						<width>'$dim'</width>
						<label> STATUS </label>
						<action>'$status_proxy'</action>
						<action type="refresh">terminale</action>
					</button>
				</frame>
				
				<frame My IP>
					<button tooltip-text="Controllo IP">
						<input file>/usr/share/icons/Humanity/actions/24/stock_media-stop.svg</input>
						<width>'$dim'</width>
						<label> MY IP </label>
						<action>'$my_ip'</action>
						<action type="refresh">terminale</action>
					</button>
				</frame>
								
				<frame Iceweasel Tor>
					<button tooltip-text="Iceweasel Tor">
						<input file>/opt/anonsurf/icons/iceweasel_tor.png</input>
						<width>'$dim'</width>
						<label> Iceweasel TOR </label>
						<action>'$iceweasel_tor'</action>
						<action type="refresh">terminale</action>
					</button>
				</frame>
				
				<frame Tor Chat>
					<button tooltip-text="Tor Chat">
						<input file>/usr/share/torchat//opt/anonsurf/icons/torchat.png</input>
						<width>'$dim'</width>
						<label> TOR Chat </label>
						<action>'$tor_chat'</action>
						<action type="refresh">terminale</action>
					</button>
				</frame>
				
				<frame Pandora Box>
					<button tooltip-text="Pandora Box Manager">
						<input file>/usr/share/icons/Humanity/actions/24/stock_media-stop.svg</input>
						<width>'$dim'</width>
						<label> Pandora Box </label>
						<action>'$pandora_manager'</action>
						<action type="refresh">terminale</action>
					</button>
				</frame>
		
				<frame I2P>
					<button tooltip-text="Start I2P">
						<input file>/usr/share/icons/Humanity/actions/24/start.svg</input>
						<width>'$dim'</width>
						<label> START </label>
						<action>'$start_i2p'</action>
						<action type="refresh">terminale</action>
					</button>
					<button tooltip-text="Stop I2P">
						<input file>/usr/share/icons/Humanity/actions/24/stop.svg</input>
						<width>'$dim'</width>
						<label> STOP </label>
						<action>'$stop_i2p'</action>
						<action type="refresh">terminale</action>
					</button>
				</frame>
			</frame>
			<frame>
				<terminal argv0="/bin/bash" space-expand="true" space-fill="true" background-transparent="true" background-saturation="0.2" background-tint-color="#223" text-foreground-color="#fff">
					<variable>terminale</variable>
					<input file>'$tmp_file'</input>
				</terminal>
			</frame>
    </hbox>
	</vbox>
</window>
'
gtkdialog --program=MAIN_DIALOG

sed -i 'd' > $tmp_file

exit
